### ISSUE TITLE
HELP WANTED - is this SDKs available in Swift?

### ISSUE THREAD

**Issue by DhavalUmraliya** [htangsmart/FitCloudPro-SDK-iOS#14]
Hello 
I am looking for sdk in swift language. kindly draw ne suggestion or another approch.
@yurikoles @pcjbird @htangsmart 

Thanks:)
Dhaval

**Comment by yurikoles** [comment]
But why? You may write your own code in Swift, Xcode will [transparently map Objective-C API to Swift](https://developer.apple.com/documentation/swift/importing-objective-c-into-swift) on the fly.

**Comment by pcjbird** [comment]
@yurikoles Great!
