### ISSUE TITLE
Problem with building FitCloudKit 1.2.6

### ISSUE THREAD

**Issue by hanayashiki** [htangsmart/FitCloudPro-SDK-iOS#18]
I got the following error when building 1.2.6

```
iosdfulibrary could not find or use auto-linked framework 'iosdfulibrary'
```

No problem when downgrading to 1.2.5

**Comment by avinashamanjha251** [comment]
works fine for me 

![Screenshot 2023-01-31 at 11 28 07 AM](https://user-images.githubusercontent.com/27722634/215678224-6697fa22-70ec-4977-9a1c-06c2e5bbf142.png)
