### ISSUE TITLE
XCode14.2 不支持 AliCloudIotKitAdvance.framework 

### ISSUE THREAD

**Issue by xusion** [htangsmart/FitCloudPro-SDK-iOS#20]
XCode14.2 编译错误：

/AliCloudIotKitAdvance.framework/Modules/AliCloudIotKitAdvance.swiftmodule/arm64-apple-ios.private.swiftinterface:1:1: Failed to build module 'AliCloudIotKitAdvance'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.7 (swiftlang-5.7.0.127.4 clang-1400.0.29.50)', while this compiler is 'Apple Swift version 5.7.2 (swiftlang-5.7.2.135.5 clang-1400.0.29.51)'). Please select a toolchain which matches the SDK.

请问可以更新这个SDK吗？

**Comment by pcjbird** [comment]
The Aliot feature is not totally released now.
