### ISSUE TITLE
How can I modify the dial

### ISSUE THREAD

**Issue by fcmeca** [htangsmart/FitCloudPro-SDK-iOS#24]
I'm trying to modify the predefined dial, I want to show in my app the dials that are assigned in speed dial and modify the predefined dial in the watch, but I can't find the way to do it, thanks.

**Comment by fcmeca** [comment]
i have a watch face download from server and loaded in watch and I want change it with local dial.

Found this method in FitCloudWFKit:

[FitCloudWFKit modifyWatchfaceBinPushIndexTo:1 fromTemplateBin:templateBinPath logging:^(FCWKLOGLEVEL level, NSString * _Nullable message) {
   ...
}
 but I don't know if this is the correct method for this action.

Any help???

Thanks!

**Comment by pcjbird** [comment]
> 

This api helps you to create a new watchface base on a template. After you create the new watchface, please invoke FitCloudDFUKit to send it to the smartwatch.
