### ISSUE TITLE
Add generic notification support

### ISSUE THREAD

**Issue by jbonofre** [htangsmart/FitCloudPro-SDK-iOS#3]
It would be great to support any kind of notification (both on Android and iOS).

**Comment by jbonofre** [comment]
Any chance to push to band any kind of notification ? I would be happy to help but not sure it's possible.

**Comment by jbonofre** [comment]
Here's a proposal of notification support:
- slack
- google hangout
- linkedin
- youtube

Basically, any notification support would be great ! Thanks !

**Comment by pcjbird** [comment]
You should contact our business, thanks.

**Comment by jbonofre** [comment]
@pcjbird thanks for your feedback. Any contact address I can use ?

**Comment by pcjbird** [comment]
> @pcjbird thanks for your feedback. Any contact address I can use ?

I think your business can contact us. We only provide technical support in GitHub. Thanks.
