### ISSUE TITLE
同步数据没有接收到同步结束的信息，导致一直卡住无法发送命令

### ISSUE THREAD

**Issue by yeejoe** [htangsmart/FitCloudPro-SDK-iOS#5]
同步数据开始之后没有接收到同步结束的信息，导致一直卡住无法发送命令。即使发送指令也会因为“同步数据中”而收到Error

我开发的环境：
FitCloudKit V1.2.1 iOS - Swift

**Comment by pcjbird** [comment]
请按照问题模版反馈你的问题：https://github.com/htangsmart/FitCloudPro-SDK-iOS/blob/master/issue_template.pdf
这种情况，你需要提供详细的日志信息。
