### ISSUE TITLE
开启ECG后，通过 delegate 收到的数据在任何状态都是一模一样的

### ISSUE THREAD

**Issue by yeejoe** [htangsmart/FitCloudPro-SDK-iOS#6]
开启ECG后，通过 delegate 收到的数据在任何状态都是一模一样的

我开发的环境：
FitCloudKit V1.2.1 iOS - Swift

**Comment by pcjbird** [comment]
请按照问题模版反馈你的问题：https://github.com/htangsmart/FitCloudPro-SDK-iOS/blob/master/issue_template.pdf
这种情况，你需要提供详细的日志信息。
