### ISSUE TITLE
开启ECG后，通过 delegate 收到的数据在任何状态都是一模一样的

### ISSUE THREAD

**Issue by yeejoe** [htangsmart/FitCloudPro-SDK-iOS#7]
1. Issue 发生的时间
- 没有特定时间，开启心电图测量之后

2. Issue 表现
开启ECG后，手环界面显示“测量心电图中，请触碰金属面”，没有出现任何倒数，之后通过 delegate 收到的数据在任何状态都是一模一样的

3. Issue 截图
- 
![IMG_2792](https://user-images.githubusercontent.com/9253220/100975820-93af8280-3579-11eb-83c5-1e80bce062b0.jpg)

4. 如何重现
连接手环，等待数据同步后，关闭所有实时测量功能，成功后开启心电图实时测量

5. 预期表现
接受正常的心电数据，而不是一直重复一模一样的心电

6. 测试环境
设备： iPhone X
iOS 版本： 14.0.1
Xcode 版本：12.0
FitCloudKit V1.2.1 - Swift

7. 日志文件
-

**Comment by pcjbird** [comment]
你好，请将日志文件发给我们，我想你应该通过商务联系我们。
